### ISSUE TITLE
Silent hubot, joins talker twice

### ISSUE THREAD

**Issue by rdrey** [unixcharles/hubot-talker#2]
Each time I fire up hubot it joins my talker room successfully, but I get two joining notifications in the chat room.

Unfortunately the bot doesn't react to any commands. It is called "Pedanto" in talkerapp and I start it with the `bin/hubot -a talker -n Pedanto` flag, but neither

```
@Pedanto help
```

or

```
Pedanto help
```

produce any reply. I do see the talker messages arrive in the running hubot's console output, though.

**Comment by unixcharles** [comment]
Hi @rdrey 

I just updated my own bot to edge hubot (2.1.2) and it work fine for me.

Here is my npm package.json

``` json
{
  "name":        "teambot",
  "version":     "0.1.1",

  "repository" : {
    "type" : "git",
    "url" : "http://github.com/teambot/teambot.git"
  },

  "dependencies": {
    "hubot": ">= 2.1.2",
    "hubot-talker": ">= 1.0.1",
    "hubot-scripts": ">= 2.0.4",
    "optparse": "1.0.1",
    "redis": ">= 0.6.7"
  }
}
```

My Procfile

```
$ cat Procfile
app: bin/hubot -a talker -n Teambot
```

My environment variable config

```
HUBOT_TALKER_ROOMS=860 HUBOT_TALKER_TOKEN=7c1********************************467
```

If you could gist me the log and your `package.json` so I can try to reproduce locally.

**Comment by rdrey** [comment]
Hi @unixcharles 

it's interesting that you have your own package.json for your teambot. I just edited the hubot's package.json to add the "hubot-talker" dependency, but left the package's "name" as hubot. I initially had issues with hubot-talker not finding the hubot module, but I `npm install hubot/` from the parent directory, then hubot-talker finds it.

I'm not deploying on heroku, but on a pretty clean linode instance. Where is the bin/hubot located if you nest the hubot in your own package?

`Connected to room 2849.
To room 2849: {"room":"2849","token":"9dbxxxx5f4e","type":"connect"}
From room 2849: {"type":"connected","user":{"name":"Pedanto","id":8768,"email":"dryrai001@uct.ac.za"}}
From room 2849: {"type":"join","id":"d448916010ae012f529212313d01ccc7","time":1324766697,"user":{"name":"Pedanto","id":8768,"email":"dryrai001@uct.ac.za"}}
From room 2849: {"type":"users","users":[{"name":"rdrey","id":8767,"email":"rdrey1@gmail.com"},{"name":"Pedanto","id":8768,"email":"dryrai001@uct.ac.za"}],"id":"d448a63010ae012f529212313d01ccc7"}
From room 2849: {"time":1324766718,"id":"e0e9bc9010ae012f529412313d01ccc7","type":"message","content":"@Pedanto help","user":{"name":"rdrey","id":8767,"email":"rdrey1@gmail.com"}}
To room 2849: {"type":"ping"}`

Is it normal that the bot receives its own join event?

**Comment by unixcharles** [comment]
> it's interesting that you have your own package.json for your teambot. 

You have no `package.json`? did you use the generator?

```
bin/hubot -c ../my_hubot_bot
```

> Where is the bin/hubot located if you nest the hubot in your own package?

I don't have my own hubot package, its just an application that use hubot and npm do the dependency management.

> Is it normal that the bot receives its own join event?

Yes, this is how talker protocol work. When you subscribe to a channel, you receive all the event no matter if they are coming from you or someone else.

The log look normal, it look just like mine. I don't understand what his wrong with you're installation.

**Comment by unixcharles** [comment]
Let me know if you nee more help, I'll close it for now

**Comment by kitop** [comment]
I'm having this same issue with Hubot 2.1.4.
I'm on a free Talker plan, could this be related in some way?

**Comment by unixcharles** [comment]
> I'm having this same issue with Hubot 2.1.4.

Can you open an issue with reproduction step?

> I'm on a free Talker plan, could this be related in some way?

No, its unrelated. For paid plan we only add unlimited logging and more storage, the rest of the application is the same.

**Comment by rdrey** [comment]
@unixcharles Sorry about my passiveness, I did manage to get hubot working after figuring out how to name it properly. I think the double notification issue still persisted, but I haven't played with hubot in a while. I will give talker & hubot another go soon.
